controller_list:
  - name: panda_arm_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [panda_joint_x, panda_joint_y, panda_joint_theta, schunk_pw70_joint_pan, schunk_pw70_joint_tilt, panda_joint_1, panda_joint_2, panda_joint_3, panda_joint_4, panda_joint_5, panda_joint_6, panda_joint_7]
