panda_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - panda_joint_1
     - panda_joint_2
     - panda_joint_3
     - panda_joint_4
     - panda_joint_5
     - panda_joint_6
     - panda_joint_7
     - panda_joint_8
     - panda_joint_x
     - panda_joint_y
     - panda_joint_theta
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      panda_joint_1: {trajectory: 0.1, goal: 0.1}
      panda_joint_2: {trajectory: 0.1, goal: 0.1}
      panda_joint_3: {trajectory: 0.1, goal: 0.1}
      panda_joint_4: {trajectory: 0.1, goal: 0.1}
      panda_joint_5: {trajectory: 0.1, goal: 0.1}
      panda_joint_6: {trajectory: 0.1, goal: 0.1}
      panda_joint_7: {trajectory: 0.1, goal: 0.1}
      panda_joint_8: {trajectory: 0.1, goal: 0.1}
      panda_joint_x: {trajectory: 0.1, goal: 0.1}
      panda_joint_y: {trajectory: 0.1, goal: 0.1}
      panda_joint_theta: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - panda_joint_1
     - panda_joint_2
     - panda_joint_3
     - panda_joint_4
     - panda_joint_5
     - panda_joint_6
     - panda_joint_7
     - panda_joint_8
     - panda_joint_x
     - panda_joint_y
     - panda_joint_theta
